#! /usr/bin/ruby
require 'fileutils'

xcode_template_dir = File.expand_path "~/Library/Developer/Xcode/Templates"

project_templates_dir = File.join(xcode_template_dir, "Project Templates", "Application")
file_templates_dir = File.join(xcode_template_dir, "File Templates")

osx_file_template_dir = File.join(file_templates_dir, 'Cocoa');
iphone_file_template_dir = File.join(file_templates_dir, 'Cocoa Touch');
FileUtils.mkdir_p(osx_file_template_dir)
FileUtils.mkdir_p(iphone_file_template_dir)
FileUtils.mkdir_p(project_templates_dir)

cedar_osx_file_template_dir = File.join(osx_file_template_dir, 'Cedar spec.xctemplate');
cedar_iphone_file_template_dir = File.join(iphone_file_template_dir, 'Cedar spec.xctemplate');
cedar_project_dir = File.join(project_templates_dir, 'Cedar App.xctemplate');
cedar_iphone_project_dir = File.join(project_templates_dir, 'Cedar Touch App.xctemplate');

system(%Q[rm -rf "#{cedar_project_dir}"])
system(%Q[rm -rf "#{cedar_osx_file_template_dir}"])
puts "Copying OS X project templates to #{cedar_project_dir}"
system(%Q[cp -R Project/osx "#{cedar_project_dir}"])
puts "Copying OS X file templates to #{cedar_osx_file_template_dir}"
system(%Q[cp -R File/osx "#{cedar_osx_file_template_dir}"])

system(%Q[rm -rf "#{cedar_iphone_project_dir}"])
system(%Q[rm -rf "#{cedar_iphone_file_template_dir}"])
puts "Copying iPhone project templates to #{cedar_iphone_project_dir}"
system(%Q[cp -R Project/osx "#{cedar_project_dir}"])
puts "Copying iPhone file templates to #{cedar_iphone_file_template_dir}"
system(%Q[cp -R File/osx "#{cedar_iphone_file_template_dir}"])
